import pygame

keymap = {
    pygame.K_0: 0x27,
    pygame.K_1: 0x1e,
    pygame.K_2: 0x1f,
    pygame.K_3: 0x20,
    pygame.K_4: 0x21,
    pygame.K_5: 0x22,
    pygame.K_6: 0x23,
    pygame.K_7: 0x24,
    pygame.K_8: 0x25,
    pygame.K_9: 0x26,
    #  pygame.K_AMPERSAND: ,
    #  pygame.K_ASTERISK: ,
    #  pygame.K_AT: ,
    pygame.K_BACKQUOTE: 0x35,
    pygame.K_BACKSLASH: 0x31,
    pygame.K_BACKSPACE: 0x2a,
    #  pygame.K_BREAK: ,
    pygame.K_CAPSLOCK: 0x39,
    #  pygame.K_CARET: ,
    pygame.K_CLEAR: 0x9c,
    #  pygame.K_COLON: ,
    pygame.K_COMMA: 0x36,
    pygame.K_DELETE: 0x4c,
    #  pygame.K_DOLLAR: ,
    pygame.K_DOWN: 0x51,
    pygame.K_END: 0x4d,
    pygame.K_EQUALS: 0x2e,
    pygame.K_ESCAPE: 0x29,
    #  pygame.K_EURO: ,
    #  pygame.K_EXCLAIM: ,
    pygame.K_F1: 0x3a,
    pygame.K_F10: 0x43,
    pygame.K_F11: 0x44,
    pygame.K_F12: 0x45,
    pygame.K_F13: 0x68,
    pygame.K_F14: 0x69,
    pygame.K_F15: 0x6a,
    pygame.K_F2: 0x3b,
    pygame.K_F3: 0x3c,
    pygame.K_F4: 0x3d,
    pygame.K_F5: 0x3e,
    pygame.K_F6: 0x3f,
    pygame.K_F7: 0x40,
    pygame.K_F8: 0x41,
    pygame.K_F9: 0x42,
    #  pygame.K_FIRST: ,
    #  pygame.K_GREATER: ,
    #  pygame.K_HASH: ,
    pygame.K_HELP: 0x75,
    pygame.K_HOME: 0x4a,
    pygame.K_INSERT: 0x49,
    pygame.K_KP0: 0x62,
    pygame.K_KP1: 0x59,
    pygame.K_KP2: 0x5a,
    pygame.K_KP3: 0x5b,
    pygame.K_KP4: 0x5c,
    pygame.K_KP5: 0x5d,
    pygame.K_KP6: 0x5e,
    pygame.K_KP7: 0x5f,
    pygame.K_KP8: 0x60,
    pygame.K_KP9: 0x61,
    pygame.K_KP_DIVIDE: 0x54,
    pygame.K_KP_ENTER: 0x58,
    #  pygame.K_KP_EQUALS: 0,
    pygame.K_KP_MINUS: 0x56,
    pygame.K_KP_MULTIPLY: 0x55,
    pygame.K_KP_PERIOD: 0x63,
    pygame.K_KP_PLUS: 0x57,
    #  pygame.K_LAST: ,
    pygame.K_LEFT: 0x50,
    pygame.K_LEFTBRACKET: 0x2f,
    #  pygame.K_LEFTPAREN: ,
    pygame.K_LESS: 0x64,
    pygame.K_MENU: 0x65,
    pygame.K_MINUS: 0x2d,
    #  pygame.K_MODE: ,
    pygame.K_NUMLOCK: 0x53,
    pygame.K_PAGEDOWN: 0x4e,
    pygame.K_PAGEUP: 0x4b,
    pygame.K_PAUSE: 0x48,
    pygame.K_PERIOD: 0x37,
    #  pygame.K_PLUS: ,
    #  pygame.K_POWER: ,
    pygame.K_PRINT: 0x46,
    #  pygame.K_QUESTION: ,
    pygame.K_QUOTE: 0x34,
    #  pygame.K_QUOTEDBL: ,
    pygame.K_RETURN: 0x28,
    pygame.K_RIGHT: 0x4f,
    pygame.K_RIGHTBRACKET: 0x30,
    #  pygame.K_RIGHTPAREN: ,
    pygame.K_SCROLLOCK: 0x47,
    pygame.K_SEMICOLON: 0x33,
    pygame.K_SLASH: 0x38,
    pygame.K_SPACE: 0x2c,
    pygame.K_SYSREQ: 0x9a,
    pygame.K_TAB: 0x2b,
    #  pygame.K_UNDERSCORE: ,
    #  pygame.K_UNKNOWN: ,
    pygame.K_UP: 0x52,
    pygame.K_a: 0x04,
    pygame.K_b: 0x05,
    pygame.K_c: 0x06,
    pygame.K_d: 0x07,
    pygame.K_e: 0x08,
    pygame.K_f: 0x09,
    pygame.K_g: 0x0a,
    pygame.K_h: 0x0b,
    pygame.K_i: 0x0c,
    pygame.K_j: 0x0d,
    pygame.K_k: 0x0e,
    pygame.K_l: 0x0f,
    pygame.K_m: 0x10,
    pygame.K_n: 0x11,
    pygame.K_o: 0x12,
    pygame.K_p: 0x13,
    pygame.K_q: 0x14,
    pygame.K_r: 0x15,
    pygame.K_s: 0x16,
    pygame.K_t: 0x17,
    pygame.K_u: 0x18,
    pygame.K_v: 0x19,
    pygame.K_w: 0x1a,
    pygame.K_x: 0x1b,
    pygame.K_y: 0x1c,
    pygame.K_z: 0x1d,
}

modifiers = {
    pygame.K_LSHIFT: 1,
    pygame.K_LSUPER: 3,
    pygame.K_LALT: 2,
    pygame.K_LCTRL: 0,
    pygame.K_RSHIFT: 5,
    pygame.K_RSUPER: 7,
    pygame.K_RALT: 6,
    pygame.K_RCTRL: 4,
    pygame.K_MODE: 6,
}
